import { GeneratedPaper } from '@/types';

const difficultyColor: Record<string, string> = {
  easy: '#16a34a',
  medium: '#d97706',
  hard: '#dc2626',
};

export async function downloadPaperAsPDF(
  paper: GeneratedPaper,
  studentInfo: { name: string; rollNumber: string; section: string },
  assignmentTitle: string
) {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const pageWidth = 210;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 20;

  const checkPageBreak = (needed = 10) => {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(assignmentTitle, pageWidth / 2, y, { align: 'center' });
  y += 8;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Subject: ${paper.subject}  |  Class: ${paper.className}  |  Duration: ${paper.duration}`, pageWidth / 2, y, { align: 'center' });
  y += 6;
  doc.text(`Total Marks: ${paper.totalMarks}`, pageWidth / 2, y, { align: 'center' });
  y += 8;

  // Divider
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  // Student Info
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', margin, y);
  y += 6;

  doc.setFont('helvetica', 'normal');
  const sInfoY = y;
  doc.text(`Name: ${studentInfo.name || '_________________________'}`, margin, sInfoY);
  doc.text(`Roll No: ${studentInfo.rollNumber || '____________'}`, margin + 80, sInfoY);
  doc.text(`Section: ${studentInfo.section || '______'}`, margin + 140, sInfoY);
  y += 10;

  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Sections
  for (const section of paper.sections) {
    checkPageBreak(20);

    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(` [${section.totalMarks} Marks]`, margin + doc.getTextWidth(section.title) + 2, y);
    y += 6;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'italic');
    doc.text(section.instruction, margin, y);
    y += 6;

    for (const q of section.questions) {
      checkPageBreak(15);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      const qLabel = `${q.id}. `;
      const qText = q.text;
      const wrapped = doc.splitTextToSize(qText, contentWidth - 30);

      doc.text(qLabel, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(wrapped, margin + 10, y);

      // Difficulty badge
      const diffX = pageWidth - margin - 30;
      doc.setFontSize(8);
      doc.setTextColor(difficultyColor[q.difficulty] || '#333');
      doc.text(`[${q.difficulty.toUpperCase()}]`, diffX, y);
      doc.setTextColor(0, 0, 0);

      // Marks
      doc.setFontSize(9);
      doc.text(`${q.marks}M`, pageWidth - margin - 5, y, { align: 'right' });

      y += wrapped.length * 6 + 3;
      checkPageBreak(5);
    }
    y += 6;
  }

  // Footer
  doc.setFontSize(9);
  doc.setFont('helvetica', 'italic');
  doc.text(`Generated by QuestAI • ${new Date().toLocaleDateString()}`, pageWidth / 2, 285, { align: 'center' });

  doc.save(`${assignmentTitle.replace(/\s+/g, '_')}_question_paper.pdf`);
}
